### ISSUE TITLE
Webpack/babel/reactjs not working

### ISSUE THREAD

**Issue by MTRNord** [manelpb/videojs-qualityselector#2]
I use a reactjs webpack setup. I import videojs via npm and get the following error:

```
C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:151
_videoJs2["default"].plugin('qualityselector', qualityselector);
                    ^
TypeError: Cannot read property 'plugin' of undefined
    at Object.<anonymous> (C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:151:21)
    at Object.1 (C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:158:4)
    at s (C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:7:636)
    at e (C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:7:807)
    at C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:7:825
    at a (C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:7:88)
    at Object.<anonymous> (C:\Users\marce\Documents\dev\ff-stream-web\node_modules\videojs-qualityselector\dist\videojs-qualityselector.js:7:338)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
C:\Users\marce\Documents\dev\ff-stream-web\tools\runServer.js:73
          throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);
          ^

Error: Server terminated unexpectedly with code: 1 signal: null
    at ChildProcess.server.once (C:/Users/marce/Documents/dev/ff-stream-web/tools/runServer.js:53:17)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
error Command failed with exit code 1.
```

**Comment by manelpb** [comment]
Can you share your webpack config file? So I could test it better

**Comment by MTRNord** [comment]
Well give me some time I actually need to search that code first :) I will upload it to github and link it asap

**Comment by MTRNord** [comment]
@manelpb project is up at https://github.com/MTRNord/ff-stream-web (it is from a template as you see)
